[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]

ureq = "=2.12.1"
thiserror = { workspace=true }
chrono = { workspace=true }
quick-xml = "0.38.3"
serde = { workspace=true }
serde_json = "1.0.143"
