[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "=2.12.1"
thiserror = { workspace=true }
chrono = { workspace=true }
quick-xml = { version = "0.38.3", features = ["serialize"] }
serde = { workspace=true }
serde_json = "1.0.143"
log = { workspace=true }
