[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
infrastructure = { path = "../infrastructure" }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

# TODO: Remove dependecy on infrastructure
